# Generated by Django 5.0.3 on 2024-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_userpost_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='caption_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
